[lb_servers]
lb1 ansible_host=172.20.0.10
lb2 ansible_host=172.20.0.11

[backend_servers]
backend1 ansible_host=172.20.0.20
backend2 ansible_host=172.20.0.21

[monitoring_back]
victoriametrics ansible_host=172.20.0.30
[monitoring_front]
grafana ansible_host=172.20.0.31


